import { FareSetting } from '../models';

export async function seedFareSettings(): Promise<any[]> {
  // Clear existing fare settings
  await FareSetting.deleteMany({});

  const fareSettings = [
    {
      vehicleType: 'economy',
      nameAr: 'اقتصادي',
      nameEn: 'Economy',
      description: 'Affordable rides for daily commute',
      descriptionAr: 'رحلات اقتصادية للتنقل اليومي',
      baseFare: 10,
      perKmRate: 3,
      perMinuteRate: 0.5,
      minimumFare: 15,
      cancellationFee: 10,
      freeCancellationMinutes: 2,
      waitingFeePerMinute: 1,
      freeWaitingMinutes: 5,
      platformFeePercentage: 20,
      surgeMultiplier: 1.0,
      maxSurgeMultiplier: 2.5,
      capacity: 4,
      icon: 'car-economy',
      isActive: true,
      peakHours: [
        { start: '07:00', end: '09:00', multiplier: 1.3, nameAr: 'ذروة الصباح' },
        { start: '17:00', end: '20:00', multiplier: 1.3, nameAr: 'ذروة المساء' },
      ],
    },
    {
      vehicleType: 'comfort',
      nameAr: 'مريح',
      nameEn: 'Comfort',
      description: 'Comfortable rides with newer cars',
      descriptionAr: 'رحلات مريحة بسيارات حديثة',
      baseFare: 15,
      perKmRate: 4,
      perMinuteRate: 0.7,
      minimumFare: 20,
      cancellationFee: 15,
      freeCancellationMinutes: 3,
      waitingFeePerMinute: 1.5,
      freeWaitingMinutes: 5,
      platformFeePercentage: 18,
      surgeMultiplier: 1.0,
      maxSurgeMultiplier: 2.5,
      capacity: 4,
      icon: 'car-comfort',
      isActive: true,
      peakHours: [
        { start: '07:00', end: '09:00', multiplier: 1.25, nameAr: 'ذروة الصباح' },
        { start: '17:00', end: '20:00', multiplier: 1.25, nameAr: 'ذروة المساء' },
      ],
    },
    {
      vehicleType: 'family',
      nameAr: 'عائلي',
      nameEn: 'Family',
      description: 'Spacious vehicles for families or groups',
      descriptionAr: 'سيارات واسعة للعائلات والمجموعات',
      baseFare: 20,
      perKmRate: 5,
      perMinuteRate: 0.8,
      minimumFare: 25,
      cancellationFee: 20,
      freeCancellationMinutes: 5,
      waitingFeePerMinute: 2,
      freeWaitingMinutes: 7,
      platformFeePercentage: 15,
      surgeMultiplier: 1.0,
      maxSurgeMultiplier: 2.0,
      capacity: 7,
      icon: 'car-family',
      isActive: true,
      peakHours: [
        { start: '07:00', end: '09:00', multiplier: 1.2, nameAr: 'ذروة الصباح' },
        { start: '17:00', end: '20:00', multiplier: 1.2, nameAr: 'ذروة المساء' },
      ],
    },
    {
      vehicleType: 'tuktuk',
      nameAr: 'توكتوك',
      nameEn: 'TukTuk',
      description: 'Quick and affordable short trips',
      descriptionAr: 'رحلات قصيرة سريعة واقتصادية',
      baseFare: 5,
      perKmRate: 2,
      perMinuteRate: 0.3,
      minimumFare: 8,
      cancellationFee: 5,
      freeCancellationMinutes: 2,
      waitingFeePerMinute: 0.5,
      freeWaitingMinutes: 3,
      platformFeePercentage: 15,
      surgeMultiplier: 1.0,
      maxSurgeMultiplier: 2.0,
      capacity: 3,
      icon: 'tuktuk',
      isActive: true,
      peakHours: [
        { start: '07:00', end: '09:00', multiplier: 1.2, nameAr: 'ذروة الصباح' },
        { start: '17:00', end: '20:00', multiplier: 1.2, nameAr: 'ذروة المساء' },
      ],
    },
    {
      vehicleType: 'motorcycle',
      nameAr: 'موتوسيكل',
      nameEn: 'Motorcycle',
      description: 'Fast delivery and single passenger rides',
      descriptionAr: 'توصيل سريع ورحلات فردية',
      baseFare: 7,
      perKmRate: 2.5,
      perMinuteRate: 0.4,
      minimumFare: 10,
      cancellationFee: 5,
      freeCancellationMinutes: 2,
      waitingFeePerMinute: 0.5,
      freeWaitingMinutes: 3,
      platformFeePercentage: 15,
      surgeMultiplier: 1.0,
      maxSurgeMultiplier: 2.0,
      capacity: 1,
      icon: 'motorcycle',
      isActive: true,
      peakHours: [
        { start: '07:00', end: '09:00', multiplier: 1.15, nameAr: 'ذروة الصباح' },
        { start: '17:00', end: '20:00', multiplier: 1.15, nameAr: 'ذروة المساء' },
      ],
    },
  ];

  const createdSettings = await FareSetting.insertMany(fareSettings);
  return createdSettings;
}
