import { User } from '../models';
import { hashPassword } from '../utils/password';

export interface SeededUser {
  _id: string;
  phone: string;
  name: string;
  role: 'passenger' | 'driver' | 'admin';
  email?: string;
}

export async function seedUsers(): Promise<SeededUser[]> {
  // Hash password for all users
  const adminPasswordHash = await hashPassword('admin123');
  const userPasswordHash = await hashPassword('123456');

  const users = [
    // Admin
    {
      phone: '+201000000000',
      name: 'مدير النظام',
      email: 'admin@wasalni.com',
      password: adminPasswordHash,
      authProvider: 'email',
      role: 'admin',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
    },

    // Active Passengers (6)
    {
      phone: '+201111111111',
      name: 'أحمد محمد',
      email: 'passenger1@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111112',
      name: 'سارة أحمد',
      email: 'passenger2@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111113',
      name: 'محمود علي',
      email: 'passenger3@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111114',
      name: 'فاطمة حسن',
      email: 'passenger4@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111115',
      name: 'عمر خالد',
      email: 'passenger5@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    // More Active Passengers (10 more)
    {
      phone: '+201111111117',
      name: 'نور الدين أحمد',
      email: 'passenger7@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111118',
      name: 'مريم حسين',
      email: 'passenger8@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111119',
      name: 'يوسف عبدالله',
      email: 'passenger9@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111120',
      name: 'هند محمود',
      email: 'passenger10@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111121',
      name: 'عبدالرحمن سعيد',
      email: 'passenger11@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111122',
      name: 'لمى إبراهيم',
      email: 'passenger12@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111123',
      name: 'طارق عمر',
      email: 'passenger13@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111124',
      name: 'سلمى خالد',
      email: 'passenger14@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    {
      phone: '+201111111125',
      name: 'رامي عادل',
      email: 'passenger15@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201111111126',
      name: 'ندى علي',
      email: 'passenger16@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'female',
    },
    // Suspended Passenger
    {
      phone: '+201111111116',
      name: 'راكب موقوف',
      email: 'suspended.passenger@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'passenger',
      isEmailVerified: true,
      isActive: false,
      language: 'ar',
    },

    // Approved Drivers (5)
    {
      phone: '+201222222221',
      name: 'محمد السائق',
      email: 'driver1@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201222222222',
      name: 'علي السائق',
      email: 'driver2@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201222222223',
      name: 'حسن السائق',
      email: 'driver3@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201222222224',
      name: 'أحمد السائق',
      email: 'driver4@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201222222225',
      name: 'كريم السائق',
      email: 'driver5@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },

    // Pending Drivers (3)
    {
      phone: '+201333333331',
      name: 'يوسف السائق',
      email: 'driver.pending1@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201333333332',
      name: 'إبراهيم السائق',
      email: 'driver.pending2@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },
    {
      phone: '+201333333333',
      name: 'مصطفى السائق',
      email: 'driver.pending3@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: true,
      language: 'ar',
      gender: 'male',
    },

    // Suspended Driver
    {
      phone: '+201444444444',
      name: 'سائق موقوف',
      email: 'suspended.driver@test.com',
      password: userPasswordHash,
      authProvider: 'email',
      role: 'driver',
      isEmailVerified: true,
      isActive: false,
      language: 'ar',
      gender: 'male',
    },
  ];

  const createdUsers = await User.insertMany(users);

  return createdUsers.map((u) => ({
    _id: u._id.toString(),
    phone: u.phone,
    name: u.name,
    role: u.role as 'passenger' | 'driver' | 'admin',
    email: u.email,
  }));
}
