#!/usr/bin/env bash
# Apply a city YAML config to all web components.
#
# Usage:
#   ./scripts/apply-city-config.sh bagour
#   ./scripts/apply-city-config.sh tanta
#
# What this script does:
#   1. Validates the YAML exists at config/cities/<slug>.yaml
#   2. Writes an active marker at .city-active (gitignored)
#   3. Patches each component's env / config with values from the YAML:
#      - backend/.env.local.city  → WASALNI_CITY=<slug>
#      - admin-dashboard/.env.local.city → NEXT_PUBLIC_CITY=<slug>, NEXT_PUBLIC_BRAND_*
#      - apps/passenger-web/.env.local.city → NEXT_PUBLIC_CITY=<slug>, NEXT_PUBLIC_BRAND_*
#      - apps/driver-web/.env.local.city    → NEXT_PUBLIC_CITY=<slug>, NEXT_PUBLIC_BRAND_*
#
# Re-run any time the city config changes.

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
SLUG="${1:-}"

if [[ -z "$SLUG" ]]; then
  echo "Usage: $0 <city-slug>"
  echo "Available cities:"
  ls "$ROOT/config/cities"/*.yaml 2>/dev/null | xargs -n1 basename | sed 's/\.yaml$//' | sed 's/^/  - /'
  exit 1
fi

CONFIG="$ROOT/config/cities/$SLUG.yaml"
if [[ ! -f "$CONFIG" ]]; then
  echo "Error: $CONFIG not found"
  exit 1
fi

echo "==> Applying city config: $SLUG"
echo "$SLUG" > "$ROOT/.city-active"

# Helper: extract YAML scalar via grep (lightweight; doesn't require yq)
yget() { grep -E "^[[:space:]]*$1:" "$CONFIG" | head -1 | sed -E "s/^[[:space:]]*$1:[[:space:]]*//; s/^[\"']//; s/[\"']$//"; }

BRAND_EN=$(yget brand_name_en)
BRAND_AR=$(yget brand_name_ar)
PRIMARY_COLOR=$(yget primary_color)
ACCENT_COLOR=$(yget accent_color)
SUPPORT_PHONE=$(yget support_phone)
SUPPORT_EMAIL=$(yget support_email)

echo "  Brand: $BRAND_EN / $BRAND_AR"
echo "  Primary color: $PRIMARY_COLOR"

# 1) Backend env override
cat > "$ROOT/backend/.env.local.city" <<EOF
# Generated by apply-city-config.sh — do not edit by hand
WASALNI_CITY=$SLUG
WASALNI_CITY_CONFIG_PATH=$CONFIG
EOF
echo "  ✓ backend/.env.local.city"

# Helper: write Next.js env for an app dir
write_next_city_env() {
  local APP_DIR="$1"
  mkdir -p "$APP_DIR"
  cat > "$APP_DIR/.env.local.city" <<EOF
# Generated by apply-city-config.sh — do not edit by hand
NEXT_PUBLIC_CITY=$SLUG
NEXT_PUBLIC_BRAND_NAME_EN=$BRAND_EN
NEXT_PUBLIC_BRAND_NAME_AR=$BRAND_AR
NEXT_PUBLIC_PRIMARY_COLOR=$PRIMARY_COLOR
NEXT_PUBLIC_ACCENT_COLOR=$ACCENT_COLOR
NEXT_PUBLIC_SUPPORT_PHONE=$SUPPORT_PHONE
NEXT_PUBLIC_SUPPORT_EMAIL=$SUPPORT_EMAIL
EOF
}

# 2) Admin dashboard env
write_next_city_env "$ROOT/admin-dashboard"
echo "  ✓ admin-dashboard/.env.local.city"

# 3) Passenger web env
write_next_city_env "$ROOT/apps/passenger-web"
echo "  ✓ apps/passenger-web/.env.local.city"

# 4) Driver web env
write_next_city_env "$ROOT/apps/driver-web"
echo "  ✓ apps/driver-web/.env.local.city"

echo
echo "✅ Applied $SLUG. Restart backend and rebuild web apps to take effect."
echo "   Next: cd backend && (source .env.local.city; pnpm dev)"
